from pydantic import BaseModel, Field
from typing import Optional

class WriterOutput(BaseModel):
    document_content: str = Field(description="The finalized, formatted content generated by the agent.")
    format_type: str = Field(description="The format of the content, e.g., 'Markdown', 'HTML', 'JSON', 'Report'")
    status: str = Field(default="SUCCESS", description="Status of the writing task.")
    error_message: Optional[str] = Field(default=None, description="Error details if generation failed.")
